### ISSUE TITLE
Incompatible with nodebb-plugin-poll

### ISSUE THREAD

**Issue by psychobunny** [frissdiegurke/nodebb-plugin-emoji-extended#15]
https://github.com/Schamper/nodebb-plugin-poll/issues/15

As said in the other issue, it's probably weird to complain about author A's plugin breaking author B's plugin, but I thought I'd put this up in the hopes that somebody knows what the problem is :)

**Comment by frissdiegurke** [comment]
Since there is no `nodebb-plugin-poll` available for the NodeBB `1.0.0` compatibility, I'm closing this.

Please report again [within the rework](https://github.com/NodeBB-Community/nodebb-plugin-emoji-extended) when it occurs once more.
