### ISSUE TITLE
display emojis in tabs

### ISSUE THREAD

**Issue by barisusakli** [frissdiegurke/nodebb-plugin-emoji-extended#18]
Right now displays everything in same modal

people/nature/objects etc should be tabs

**Comment by frissdiegurke** [comment]
Done.

I've decided to implement the tab-navigation by hand in order to disable browser-loading the emoji within the other tabs until that tab gets selected (also using native bootstrap-tabs would've required to append a hash to the url which results in scrolling the current page to bottom).
