### ISSUE TITLE
replaced image path is broken

### ISSUE THREAD

**Issue by MacounDe** [frissdiegurke/nodebb-plugin-emoji-extended#19]
The path to the replaced emoji image is broken. 

Example: 
http://osxentwicklerforum.de/_nodeBB/topic/3/smile-bug

P.S.: It would work, when removing the port number from the URL.

Plugin Version: 0.4.2-1
nodeBB Version: v0.7.0-dev

**Comment by frissdiegurke** [comment]
if you access the forum with port-forwarding and disallow access via the original port you need to remove the port from the `url` attribute of your *config.json* within NodeBB root

**Comment by MacounDe** [comment]
Ah damn! You're right. My fault.

Thank you.

**Comment by frissdiegurke** [comment]
You're welcome.
