### ISSUE TITLE
Images size

### ISSUE THREAD

**Issue by slvlirnoff** [frissdiegurke/nodebb-plugin-emoji-extended#23]
Hi there,

This plugin is working very well, thank you!

I have one issue with images size (using latest version v0.7.2)
* categories 'subtitle' or 'description' of the forums are now parsed and show the smileys, however they are displayed in the 64x64px size which is too big compared to the text.
* in notification emails the smiley are displayed in 64/64px as well which is again too big compared to the text.

Best,
Cyprien

**Comment by frissdiegurke** [comment]
Thanks for the report.

The size within emails has been working once. I've asked for help on this since I'm not able to find the issue: https://community.nodebb.org/topic/6248/email-modification-hook

The size within descriptions is fixed now.

Best regards,
FDG

**Comment by frissdiegurke** [comment]
With `v0.4.13` I use the newly introduced filter for emails (works with https://github.com/NodeBB/NodeBB/commit/45c446dac0a14ab64714312a544e8387ecfb4af7 upwards).

This way it's ensured the styles get added to the html of each email. If it doesn't work it's probably your email service which filters styles out. For example at mandrill you need to check the setting to include inline-styles.
