### ISSUE TITLE
action:email.send

### ISSUE THREAD

**Issue by barisusakli** [frissdiegurke/nodebb-plugin-emoji-extended#28]
why is this plugin using this hook? It should only be used by emailers to send an email. This causes the dashboard notice to show an emailer is installed even though its not 

https://github.com/NodeBB/NodeBB/issues/3609

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/45c446dac0a14ab64714312a544e8387ecfb4af7

you can use `filter:email.send` to modify the html to add the styles and remove `action:email.send`

**Comment by frissdiegurke** [comment]
changed. `v0.4.13` c730c63814b47bb921b1ae54db1fe5c00c4e346a

**Comment by barisusakli** [comment]
:+1:
