### ISSUE TITLE
Broken link to images

### ISSUE THREAD

**Issue by jenkin** [frissdiegurke/nodebb-plugin-emoji-extended#30]
When I compose a text (in post or in chat) the autocomplete function works well and I can see and select my emoticons. But once the content is published, the url in src attribute of img tag is broken, because of the presence of *localhost* as domain instead of the real domain. I'm running nodebb v0.8.2.

**Comment by frissdiegurke** [comment]
Please check your *NodeBB/config.json*. The `url` needs to be set properly.

**Comment by jenkin** [comment]
Argh, you're right, sorry! :smiley:
