### ISSUE TITLE
hard coded http

### ISSUE THREAD

**Issue by Code-Name-Debian** [frissdiegurke/nodebb-plugin-emoji-extended#33]
Everything seems to direct to http which is a problem because I'm using https

**Comment by frissdiegurke** [comment]
Please check your *NodeBB/config.json*. The `url` needs to be set properly.

**Comment by Code-Name-Debian** [comment]
Thanks for replying.  I changed the url but receive a lot of socket error notices.  Disabling your add-on resolved almost all of them except for 1.

Firefox can't establish a connection to the server at wss://sociallyuncensored.com/socket.io/?EIO=3&transport=websocket&sid=iMcxs_6FDyMXzhefAAAH.

Clearly I have more search to do.
