### ISSUE TITLE
incorrect image path

### ISSUE THREAD

**Issue by eisneim** [frissdiegurke/nodebb-plugin-emoji-extended#34]
i use nginx for proxy so in my config.js, the url is 127.0.0.1,

did a curl and  image url in html is: http://127.0.0.1:4567/plugins/nodebb-plugin-emoji-extended/images/repeat_one.png
 which is incorect,  how to solve this without change config.json?

**Comment by eisneim** [comment]
i'v just removed the "nconf.get('url')" in index.js to get it work;

**Comment by frissdiegurke** [comment]
Why don't you want to change the `url` of the *config.json*? It's exactly meant for this.
NodeBB (and its plugins) use this `url` property to create URLs to your board that are accessible from the outside world.

So it's recommended to use the `url` property for this and set it to `"whatever.it.takes.to.lookup.your.website.com"`.

Not using it may cause problems with other plugins/parts of NodeBB (e.g. it may be that email-notifications use this for link-creation, etc.).

**Comment by eisneim** [comment]
ok, thanks
