### ISSUE TITLE
Bug of emoji box going behind the writing section

### ISSUE THREAD

**Issue by jdk1811** [frissdiegurke/nodebb-plugin-emoji-extended#35]
It took a while to figure it out that it was caused by changing the skin of the nodebb. 

Here's a screenshot: http://i.imgur.com/sE52SyM.png

So basically, with the default skin, there's no problem, but changing it to other skins will cause this issue.

**Comment by frissdiegurke** [comment]
Fixed within 955e6768fad7d7a88e74818dc5c0e7a43c9fecde. `v0.4.17`

Thanks for reporting (and backtracking) :+1:
