### ISSUE TITLE
update to use `composer:autocomplete:init`

### ISSUE THREAD

**Issue by barisusakli** [frissdiegurke/nodebb-plugin-emoji-extended#36]
https://github.com/NodeBB/NodeBB/issues/3842

https://github.com/NodeBB/nodebb-plugin-composer-default/blob/4b324eec4164a3bb6e47fd20714c64f1b0d214c0/static/lib/composer/autocomplete.js#L10-L22

Plugin should just add its strategy into the array passed in to this hook. I was going to PR but :coffee: 

See https://github.com/julianlam/nodebb-plugin-mentions/blob/master/static/autofill.js#L9 for a example of how it's done in mentions plugin.

Let me know if anythings unclear.

**Comment by frissdiegurke** [comment]
* what about an equivalent event for chat-windows?
* I've added this, please notify me for publishing to npm once composer is published ;)

**Comment by barisusakli** [comment]
Yeah `chat:autocomplete:init` makes sense.

**Comment by barisusakli** [comment]
https://github.com/NodeBB/NodeBB/commit/222ef14d7f64ace1a67743d60c4b2e23edf61b14

**Comment by barisusakli** [comment]
composer 2.0.3 published
