### ISSUE TITLE
Version number on emoji composer window

### ISSUE THREAD

**Issue by psychobunny** [frissdiegurke/nodebb-plugin-emoji-extended#37]
> Emoji Extended 0.4.17

Pretty minor but I don't think end-users really need to know this, just say "Emoticons" or something

**Comment by frissdiegurke** [comment]
Within my rework this is removed, I won't publish a new version of this old one for this ;-)

**Comment by frissdiegurke** [comment]
Not present anymore in reworked version `1.0.0` (with its new home [here](https://github.com/NodeBB-Community/nodebb-plugin-emoji-extended))
