### ISSUE TITLE
Custom / modifiable emojis?

### ISSUE THREAD

**Issue by Incognitov** [frissdiegurke/nodebb-plugin-emoji-extended#38]
Just a suggestion whether it would be possible for you to support custom emojis that the user can create with custom emoji codes, or modify current emojis by either changing the emoji itself or the code for it?

Thanks.

**Comment by frissdiegurke** [comment]
There is currently a complete rework with plenty of new features in a private repository of mine (it's not ready for public yet).
ETA: 1-2 weeks :wink: 

It will support custom emoji (only via static files within first release).

**Comment by frissdiegurke** [comment]
It's released and its new home is https://github.com/NodeBB-Community/nodebb-plugin-emoji-extended

There is support for custom files via the [nodebb-plugin-emoji-static](https://github.com/NodeBB-Community/nodebb-plugin-emoji-static) plugin. Although its just very basic support for now (you need file-system access by-hand). This might change sooner or later...
