### ISSUE TITLE
should autocomplete move to core?

### ISSUE THREAD

**Issue by barisusakli** [frissdiegurke/nodebb-plugin-emoji-extended#6]
Trying to make a plugin that will replace :fa-star: with `<i class="fa fa-star"></i>`. I am having trouble integrating it with text complete since all that stuff is in this plugin.

I tried calling 
```
$('textarea').textcomplete([
  { //add new strategy
    match: /(^|\s):(\w*)$/,
    search: function (term, callback) {
     callback(['fa-star', 'fa-hammer']);
    },
    replace: function (value) {
      return '$1:' + value + ': ';
    },
    template: function(value) {
      return '<i class="fa ' + value + '"></i>';
    }
  }
]);
```

But I didn't see fa-star and fa-hammer in the auto complete list. I see them if I change the match from `:` to something else. 

It would be cool if this was in core and then we add hooks so that search and template parts can be modified by plugins here is some brain dump code.

```
//in core
$('textarea').textcomplete([
{
  match: 'same regex from this plugin',
  search: function(term, callback) {
       //this will do a plugins.fireHook('filter:textcomplete.search', term, callback);
       // or figure out client side filters >_>
       socket.emit('composer:textcomplete.search', term, function(err, results) {
            callback(results);
       });
  },
  replace: function(value) {  },
  template: function(value) {
     //same deal as search here, let plugins check value and return the correct template
  }
}]);
```
Let me know if there is a better/easier way.

**Comment by frissdiegurke** [comment]
outdated. textcomplete got included within core (see #20)
